kind: pipeline
name: pytest_demo
type: docker

trigger:
  branch:
    - master
  event:
    - push

steps:
- name: run pytest
  image: lzwang/py396
  commands:
  - pip install -r requirements.txt
  - pytest test.py